version: '3.8'
services:
  java-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-servlet-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m